import type { BlockRegistryEntry } from '../types';
import {
  validateBarHorizontalData,
  validateLineEditorialData,
  validateComparisonKpiData,
  validateTableEnrichedData,
  validateSmallMultipleData,
} from '../validation/block-data';

export const BREG: Record<string, BlockRegistryEntry> = {
  eyebrow_tag:{cat:"text",name:"Eyebrow",status:"optional_default",allowedSections:["header"],maxPerSection:1,dp:{text:"STATISTICS CANADA \u00B7 TABLE 18-10-0004"},cst:{maxChars:60,maxLines:1},ctrl:[{k:"text",t:"text",l:"Tag",ml:60}],
    guard:(p)=>typeof p.text==="string"},
  headline_editorial:{cat:"text",name:"Headline",status:"required_editable",allowedSections:["header"],maxPerSection:1,dp:{text:"Canadian Mortgage Rates\nHit 15-Year High",align:"left"},cst:{maxChars:80,maxLines:3},ctrl:[{k:"text",t:"textarea",l:"Headline",ml:80},{k:"align",t:"seg",l:"Align",opts:["left","center","right"]}],
    guard:(p)=>typeof p.text==="string"&&["left","center","right"].includes(p.align||"left")},
  subtitle_descriptor:{cat:"text",name:"Subtitle",status:"optional_default",allowedSections:["header","context"],maxPerSection:1,dp:{text:"Average 5-year fixed rate, March 2026"},cst:{maxChars:120,maxLines:2},ctrl:[{k:"text",t:"text",l:"Subtitle",ml:120}],
    guard:(p)=>typeof p.text==="string"},
  hero_stat:{cat:"data",name:"Hero Number",status:"required_editable",allowedSections:["hero"],maxPerSection:1,dp:{value:"6.73%",label:"5-year fixed rate"},cst:{maxChars:10},ctrl:[{k:"value",t:"text",l:"Value",ml:10},{k:"label",t:"text",l:"Label",ml:60}],
    guard:(p)=>typeof p.value==="string"},
  delta_badge:{cat:"data",name:"Delta Badge",status:"optional_default",allowedSections:["hero","context"],maxPerSection:1,dp:{value:"+247 bps since Jan 2022",direction:"negative"},cst:{maxChars:40},ctrl:[{k:"value",t:"text",l:"Delta",ml:40},{k:"direction",t:"seg",l:"Dir",labelKind:"short_label",opts:["positive","negative","neutral"]}],
    guard:(p)=>typeof p.value==="string"&&["positive","negative","neutral"].includes(p.direction||"neutral")},
  body_annotation:{cat:"text",name:"Annotation",status:"optional_available",allowedSections:["context","chart"],maxPerSection:2,dp:{text:"Rates represent posted rates from chartered banks"},cst:{maxChars:200,maxLines:4},ctrl:[{k:"text",t:"textarea",l:"Note",ml:200}],
    guard:(p)=>typeof p.text==="string"},
  source_footer:{cat:"text",name:"Source",status:"required_locked",allowedSections:["footer"],maxPerSection:1,dp:{text:"Source: Statistics Canada, Table 18-10-0004-01",methodology:""},cst:{maxChars:200},ctrl:[{k:"text",t:"text",l:"Source",ml:200},{k:"methodology",t:"text",l:"Method",labelKind:"short_label",ml:200}],
    guard:(p)=>typeof p.text==="string"},
  brand_stamp:{cat:"struct",name:"Brand",status:"required_locked",allowedSections:["footer"],maxPerSection:1,dp:{position:"bottom-right"},ctrl:[{k:"position",t:"seg",l:"Position",opts:["bottom-left","bottom-right"]}],
    guard:(p)=>["bottom-left","bottom-right"].includes(p.position)},
  bar_horizontal:{cat:"chart",name:"Ranked Bars",status:"required_editable",allowedSections:["chart"],maxPerSection:1,
    dp:{items:[{label:"Vancouver",value:12.8,flag:"\uD83C\uDDE8\uD83C\uDDE6",highlight:true},{label:"Toronto",value:10.2,flag:"\uD83C\uDDE8\uD83C\uDDE6",highlight:true},{label:"Hamilton",value:7.9,flag:"\uD83C\uDDE8\uD83C\uDDE6"},{label:"Victoria",value:7.6,flag:"\uD83C\uDDE8\uD83C\uDDE6"},{label:"Ottawa",value:5.8,flag:"\uD83C\uDDE8\uD83C\uDDE6"},{label:"Montreal",value:5.4,flag:"\uD83C\uDDE8\uD83C\uDDE6"},{label:"Calgary",value:4.2,flag:"\uD83C\uDDE8\uD83C\uDDE6"},{label:"Edmonton",value:3.5,flag:"\uD83C\uDDE8\uD83C\uDDE6"}],unit:"\u00D7",benchmarkValue:5.0,benchmarkLabel:"Affordable threshold",showBenchmark:true},
    ctrl:[{k:"unit",t:"text",l:"Unit suffix",ml:5},{k:"showBenchmark",t:"toggle",l:"Benchmark line"},{k:"benchmarkValue",t:"text",l:"Bench value",labelKind:"short_label",ml:10},{k:"benchmarkLabel",t:"text",l:"Bench label",labelKind:"short_label",ml:30}],
    guard: (p: any) => validateBarHorizontalData(p).valid},
  line_editorial:{cat:"chart",name:"Line Chart",status:"required_editable",allowedSections:["chart"],maxPerSection:1,
    dp:{series:[{label:"CPI All Items",data:[1.9,0.7,3.4,6.8,3.9,2.7,2.4,2.1],role:"primary"},{label:"BoC Target",data:[2,2,2,2,2,2,2,2],role:"benchmark"}],xLabels:["2019","2020","2021","2022","2023","2024","2025","2026"],yUnit:"%",showArea:true},
    ctrl:[{k:"yUnit",t:"text",l:"Y unit",ml:5},{k:"showArea",t:"toggle",l:"Area fill"}],
    guard: (p: any) => validateLineEditorialData(p).valid},
  comparison_kpi:{cat:"data",name:"KPI Compare",status:"required_editable",allowedSections:["chart","hero"],maxPerSection:1,
    dp:{items:[{label:"Population Growth",value:"3.2%",delta:"+1.4pp YoY",direction:"positive"},{label:"Net Immigration",value:"1.2M",delta:"+340K vs 2023",direction:"positive"},{label:"Housing Starts",value:"218K",delta:"\u221212% vs target",direction:"negative"}]},
    ctrl:[],
    guard: (p: any) => validateComparisonKpiData(p).valid},
  table_enriched:{cat:"chart",name:"Visual Table",status:"required_editable",allowedSections:["chart"],maxPerSection:1,
    dp:{columns:["Country","Individual","Corporate","Property","Consumption","Score"],rows:[{country:"Estonia",flag:"\uD83C\uDDEA\uD83C\uDDEA",vals:[2,2,1,18,100.0],rank:1},{country:"Latvia",flag:"\uD83C\uDDF1\uD83C\uDDFB",vals:[3,1,5,21,92.2],rank:2},{country:"New Zealand",flag:"\uD83C\uDDF3\uD83C\uDDFF",vals:[6,30,8,2,84.2],rank:3},{country:"Switzerland",flag:"\uD83C\uDDE8\uD83C\uDDED",vals:[8,10,36,3,83.6],rank:4},{country:"Lithuania",flag:"\uD83C\uDDF1\uD83C\uDDF9",vals:[10,3,7,27,79.5],rank:5},{country:"Canada",flag:"\uD83C\uDDE8\uD83C\uDDE6",vals:[31,26,25,8,66.8],rank:17},{country:"U.S.",flag:"\uD83C\uDDFA\uD83C\uDDF8",vals:[17,20,28,4,66.5],rank:18},{country:"France",flag:"\uD83C\uDDEB\uD83C\uDDF7",vals:[33,33,31,31,50.2],rank:36}]},
    ctrl:[],
    guard: (p: any) => validateTableEnrichedData(p).valid},
  small_multiple:{cat:"chart",name:"Small Multiples",status:"required_editable",allowedSections:["chart"],maxPerSection:1,
    dp:{items:[{label:"New York",flag:"\uD83C\uDDFA\uD83C\uDDF8",data:[-0.5,-1.2,-3.1,-4.5,-5.8,-6.2,-5.1,-4.8]},{label:"London",flag:"\uD83C\uDDEC\uD83C\uDDE7",data:[-0.3,-0.8,-2.5,-3.8,-5.2,-6.8,-5.5,-4.2]},{label:"Frankfurt",flag:"\uD83C\uDDE9\uD83C\uDDEA",data:[-0.2,-0.5,-1.8,-3.2,-5.5,-8.1,-10.2,-7.5]},{label:"Shanghai",flag:"\uD83C\uDDE8\uD83C\uDDF3",data:[0.1,-0.2,-1.5,-2.8,-3.5,-4.2,-5.8,-4.1]},{label:"Hong Kong",flag:"\uD83C\uDDED\uD83C\uDDF0",data:[-0.4,-1.0,-2.2,-4.1,-5.5,-7.2,-8.5,-6.8]},{label:"Tokyo",flag:"\uD83C\uDDEF\uD83C\uDDF5",data:[-0.1,-0.3,-1.2,-2.5,-4.8,-6.5,-9.8,-8.2]}],yUnit:"%"},
    ctrl:[{k:"yUnit",t:"text",l:"Y unit",ml:5}],
    guard: (p: any) => validateSmallMultipleData(p).valid},
};
