import type { CanonicalDocument, TemplateEntry, BlockProps } from '../types';
import { BREG } from './blocks';

const SCHEMA_VERSION = 1;

export function mkDoc(tid: string, tpl: TemplateEntry, over: Record<string, BlockProps> = {}): CanonicalDocument {
  const blocks: CanonicalDocument['blocks'] = {};
  let seq = 0;
  const sections = tpl.sections.map(sec => {
    const bids = sec.blockTypes.map(bt => {
      const id = `blk_${String(++seq).padStart(3, "0")}`;
      blocks[id] = { id, type: bt, props: { ...BREG[bt].dp, ...(over[bt] || {}) }, visible: true };
      return id;
    });
    return { id: sec.id, type: sec.type, blockIds: bids };
  });
  return { schemaVersion: SCHEMA_VERSION, templateId: tid, page: { size: tpl.defaultSize || "instagram_1080", background: tpl.defaultBg || "gradient_warm", palette: tpl.defaultPal || "housing" }, sections, blocks, workflow: "draft", meta: { createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: 1, history: [] } };
}

export const TPLS: Record<string, TemplateEntry> = {
  single_stat_hero:{fam:"Single Stat Hero",vr:"Number + Delta",desc:"Giant number with change",defaultPal:"housing",defaultBg:"gradient_warm",defaultSize:"instagram_1080",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"hero",type:"hero",blockTypes:["hero_stat","delta_badge"]},{id:"context",type:"context",blockTypes:["subtitle_descriptor"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}]},
  single_stat_note:{fam:"Single Stat Hero",vr:"Number + Note",desc:"Number with annotation",defaultPal:"housing",defaultBg:"gradient_radial",defaultSize:"instagram_1080",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"hero",type:"hero",blockTypes:["hero_stat"]},{id:"context",type:"context",blockTypes:["body_annotation"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{body_annotation:{text:"Rates represent posted rates from chartered banks."}}},
  single_stat_minimal:{fam:"Single Stat Hero",vr:"Minimal",desc:"Clean, centered",defaultPal:"neutral",defaultBg:"solid_dark",defaultSize:"twitter",sections:[{id:"header",type:"header",blockTypes:["headline_editorial"]},{id:"hero",type:"hero",blockTypes:["hero_stat"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"Bank of Canada\nHolds Rates Steady",align:"center"},hero_stat:{value:"4.50%",label:"Overnight rate"},source_footer:{text:"Source: Bank of Canada"}}},
  stat_comparison:{fam:"Single Stat Hero",vr:"Before / After",desc:"Two numbers contrasted",defaultPal:"economy",defaultBg:"gradient_midnight",defaultSize:"instagram_1080",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"hero",type:"hero",blockTypes:["hero_stat","delta_badge"]},{id:"context",type:"context",blockTypes:["subtitle_descriptor","body_annotation"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"Cost of Living\nOutpaces Wages"},eyebrow_tag:{text:"INSIGHT \u00B7 ECONOMY \u00B7 2026"},hero_stat:{value:"$74K",label:"Median household income"},delta_badge:{value:"+2.1% vs +4.8% CPI",direction:"negative"},subtitle_descriptor:{text:"Income grew 2.1% while cost of living rose 4.8%"},body_annotation:{text:"The gap between wage growth and inflation has widened for 3 consecutive years."},source_footer:{text:"Source: Statistics Canada, Labour Force Survey"}}},
  insight_card:{fam:"Insight Card",vr:"Fact + Context",desc:"Key insight with analysis",defaultPal:"government",defaultBg:"gradient_warm",defaultSize:"instagram_port",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"hero",type:"hero",blockTypes:["hero_stat","delta_badge"]},{id:"context",type:"context",blockTypes:["body_annotation"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"Federal Deficit\nReaches Record High"},eyebrow_tag:{text:"CHARTED: \u00B7 FISCAL POLICY"},hero_stat:{value:"$61.9B",label:"Projected deficit"},delta_badge:{value:"+$21.8B vs estimate",direction:"negative"},body_annotation:{text:"PBO projects deficit 40% higher than forecast."},source_footer:{text:"Source: Parliamentary Budget Officer, March 2026"}}},
  social_quote:{fam:"Insight Card",vr:"Social Post",desc:"Shareable stat",defaultPal:"society",defaultBg:"dot_grid",defaultSize:"instagram_1080",sections:[{id:"header",type:"header",blockTypes:["headline_editorial"]},{id:"hero",type:"hero",blockTypes:["hero_stat"]},{id:"context",type:"context",blockTypes:["subtitle_descriptor"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"Canada Added More People\nThan Any Year in History",align:"center"},hero_stat:{value:"1.27M",label:"Net population growth, 2025"},subtitle_descriptor:{text:"Equivalent to adding Calgary in one year"},source_footer:{text:"Source: Statistics Canada"}}},
  ranked_bar_simple:{fam:"Ranked Bars",vr:"Simple Ranking",desc:"Horizontal bars by value",defaultPal:"housing",defaultBg:"gradient_midnight",defaultSize:"reddit",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"chart",type:"chart",blockTypes:["bar_horizontal"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"Housing Price-to-Income Ratio\nAcross Major Canadian Cities"},eyebrow_tag:{text:"RANKED: \u00B7 HOUSING AFFORDABILITY \u00B7 Q4 2025"},source_footer:{text:"Source: CMHC, Q4 2025"}}},
  line_area:{fam:"Line Editorial",vr:"Single + Area",desc:"Time series with area fill",defaultPal:"government",defaultBg:"gradient_warm",defaultSize:"twitter",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"chart",type:"chart",blockTypes:["line_editorial"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"Canada's Inflation Journey:\nFrom Pandemic to New Normal"},eyebrow_tag:{text:"CHARTED: \u00B7 CPI \u00B7 2019\u20132026"},source_footer:{text:"Source: Statistics Canada"}}},
  comparison_3kpi:{fam:"Comparison",vr:"3 KPI Cards",desc:"Three metrics side by side",defaultPal:"society",defaultBg:"gradient_radial",defaultSize:"instagram_1080",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"chart",type:"chart",blockTypes:["comparison_kpi"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"Record Immigration Drives\nCanada's Population Surge"},eyebrow_tag:{text:"POPULATION GROWTH \u00B7 2025"},source_footer:{text:"Source: Statistics Canada, CMHC"}}},
  visual_table:{fam:"Visual Table",vr:"Heatmap Rankings",desc:"Table with conditional format",defaultPal:"neutral",defaultBg:"solid_dark",defaultSize:"instagram_port",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"chart",type:"chart",blockTypes:["table_enriched"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"The Best and Worst\nCountries for Taxes"},eyebrow_tag:{text:"RANKED: \u00B7 TAX COMPETITIVENESS \u00B7 2024"},source_footer:{text:"Source: Tax Foundation"}}},
  small_multiples_grid:{fam:"Small Multiples",vr:"2\u00D73 Grid",desc:"Same chart repeated",defaultPal:"economy",defaultBg:"gradient_midnight",defaultSize:"instagram_1080",sections:[{id:"header",type:"header",blockTypes:["eyebrow_tag","headline_editorial"]},{id:"chart",type:"chart",blockTypes:["small_multiple"]},{id:"footer",type:"footer",blockTypes:["source_footer","brand_stamp"]}],overrides:{headline_editorial:{text:"A Rocky Month\nfor Global Stocks"},eyebrow_tag:{text:"CHARTED: \u00B7 EQUITY INDEXES \u00B7 FEB\u2013MAR 2026"},source_footer:{text:"Source: FactSet, The New York Times"}}},
};
