// Mocks generated by Mockito 5.4.6 from annotations
// in summa_vision_admin/test/features/jobs/jobs_dashboard_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:summa_vision_admin/features/jobs/data/job_dashboard_repository.dart'
    as _i4;
import 'package:summa_vision_admin/features/jobs/domain/job.dart' as _i3;
import 'package:summa_vision_admin/features/jobs/domain/job_list_response.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJobListResponse_0 extends _i1.SmartFake
    implements _i2.JobListResponse {
  _FakeJobListResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJob_1 extends _i1.SmartFake implements _i3.Job {
  _FakeJob_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [JobDashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobDashboardRepository extends _i1.Mock
    implements _i4.JobDashboardRepository {
  @override
  _i5.Future<_i2.JobListResponse> listJobs({
    String? jobType,
    String? status,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listJobs, [], {
              #jobType: jobType,
              #status: status,
              #limit: limit,
            }),
            returnValue: _i5.Future<_i2.JobListResponse>.value(
              _FakeJobListResponse_0(
                this,
                Invocation.method(#listJobs, [], {
                  #jobType: jobType,
                  #status: status,
                  #limit: limit,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.JobListResponse>.value(
              _FakeJobListResponse_0(
                this,
                Invocation.method(#listJobs, [], {
                  #jobType: jobType,
                  #status: status,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.JobListResponse>);

  @override
  _i5.Future<_i3.Job> getJob(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#getJob, [jobId]),
            returnValue: _i5.Future<_i3.Job>.value(
              _FakeJob_1(this, Invocation.method(#getJob, [jobId])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Job>.value(
              _FakeJob_1(this, Invocation.method(#getJob, [jobId])),
            ),
          )
          as _i5.Future<_i3.Job>);

  @override
  _i5.Future<String> retryJob(String? jobId) =>
      (super.noSuchMethod(
            Invocation.method(#retryJob, [jobId]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#retryJob, [jobId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#retryJob, [jobId]),
              ),
            ),
          )
          as _i5.Future<String>);
}
