"""initial

Revision ID: 05de14ff39c6
Revises:
Create Date: 2026-04-04 06:10:28.934136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '05de14ff39c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    publication_status_enum = postgresql.ENUM(
        "DRAFT",
        "PUBLISHED",
        name="publication_status",
        create_type=False,
    )

    bind = op.get_bind()
    publication_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.Column('is_b2b', sa.Boolean(), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_hash', sa.String(length=128), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('chart_type', sa.String(length=100), nullable=False),
    sa.Column('s3_key_lowres', sa.Text(), nullable=True),
    sa.Column('s3_key_highres', sa.Text(), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('status', publication_status_enum, server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('llm_requests')
    op.drop_table('leads')
    # ### end Alembic commands ###

    bind = op.get_bind()
    publication_status_enum = postgresql.ENUM(
        "DRAFT",
        "PUBLISHED",
        name="publication_status",
        create_type=False,
    )
    publication_status_enum.drop(bind, checkfirst=True)
