"""add_composite_indexes_and_unique_constraint

Revision ID: 19d234e49fb3
Revises: ab79f3662ba3
Create Date: 2026-04-04 07:19:57.108190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d234e49fb3'
down_revision: Union[str, Sequence[str], None] = 'ab79f3662ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_lead_email_asset', ['email', 'asset_id'])
        batch_op.drop_index('ix_leads_esp_synced')
        batch_op.create_index('ix_lead_unsynced_lookup', ['esp_synced', 'esp_sync_failed_permanent', 'created_at'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_unsynced_lookup')
        batch_op.create_index('ix_leads_esp_synced', ['esp_synced'])
        batch_op.drop_constraint('uq_lead_email_asset', type_='unique')

    # ### end Alembic commands ###
