"""Add unique constraint for publication versioning

Revision ID: 421cd0e25873
Revises: 6e2e939f9cb6
Create Date: 2026-04-09 03:51:33.197104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421cd0e25873'
down_revision: Union[str, Sequence[str], None] = '6e2e939f9cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_publication_lineage_version', ['source_product_id', 'config_hash', 'version'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_publication_lineage_version', type_='unique')

    # ### end Alembic commands ###
