"""add_esp_fields_to_lead

Revision ID: 4b8b21989d14
Revises: 05de14ff39c6
Create Date: 2026-04-04 06:11:18.782422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8b21989d14'
down_revision: Union[str, Sequence[str], None] = '05de14ff39c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('esp_synced', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('leads', sa.Column('esp_sync_failed_permanent', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'esp_sync_failed_permanent')
    op.drop_column('leads', 'esp_synced')
    # ### end Alembic commands ###
