"""add_cube_catalog_table

Revision ID: 6703b5b8dfa4
Revises: 2ecef76849a5
Create Date: 2026-04-06 05:04:57.718029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6703b5b8dfa4'
down_revision: Union[str, Sequence[str], None] = '2ecef76849a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=30), nullable=False),
    sa.Column('cube_id_statcan', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('title_fr', sa.String(length=500), nullable=True),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_en', sa.String(length=255), nullable=False),
    sa.Column('survey_en', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('archive_status', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cube_catalog', schema=None) as batch_op:
        batch_op.create_index('ix_cube_catalog_cube_id', ['cube_id_statcan'], unique=False)
        batch_op.create_index('ix_cube_catalog_product_id', ['product_id'], unique=True)
        batch_op.create_index('ix_cube_catalog_subject', ['subject_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cube_catalog', schema=None) as batch_op:
        batch_op.drop_index('ix_cube_catalog_subject')
        batch_op.drop_index('ix_cube_catalog_product_id')
        batch_op.drop_index('ix_cube_catalog_cube_id')

    op.drop_table('cube_catalog')
    # ### end Alembic commands ###
