"""Add publication versioning

Revision ID: 6e2e939f9cb6
Revises: 378407da6dfa
Create Date: 2026-04-09 03:01:04.552675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2e939f9cb6'
down_revision: Union[str, Sequence[str], None] = '378407da6dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_product_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('config_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_publications_source_product_id'), ['source_product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_source_product_id'))
        batch_op.drop_column('content_hash')
        batch_op.drop_column('config_hash')
        batch_op.drop_column('version')
        batch_op.drop_column('source_product_id')

    # ### end Alembic commands ###
