"""add_indexes

Revision ID: ab79f3662ba3
Revises: 4b8b21989d14
Create Date: 2026-04-04 06:22:15.061628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab79f3662ba3'
down_revision: Union[str, Sequence[str], None] = '4b8b21989d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_leads_asset_id'), 'leads', ['asset_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_esp_synced'), 'leads', ['esp_synced'], unique=False)
    op.create_index(op.f('ix_publications_created_at'), 'publications', ['created_at'], unique=False)
    op.create_index(op.f('ix_publications_status'), 'publications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_status'), table_name='publications')
    op.drop_index(op.f('ix_publications_created_at'), table_name='publications')
    op.drop_index(op.f('ix_leads_esp_synced'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_asset_id'), table_name='leads')
    # ### end Alembic commands ###
