"""add_jobs_table

Revision ID: ffbd7002559e
Revises: 19d234e49fb3
Create Date: 2026-04-05 16:21:49.372814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbd7002559e'
down_revision: Union[str, Sequence[str], None] = '19d234e49fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', 'cancelled', name='job_status'), server_default='queued', nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index('ix_jobs_type_status', ['job_type', 'status'], unique=False)

    op.execute("""
        CREATE UNIQUE INDEX ix_jobs_dedupe_active
        ON jobs (dedupe_key)
        WHERE status IN ('queued', 'running')
          AND dedupe_key IS NOT NULL
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_jobs_dedupe_active")

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_type_status')
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))
        batch_op.drop_index('ix_jobs_created_at')

    op.drop_table('jobs')
    # ### end Alembic commands ###
